---
- name: Creating load balancer for web servers
  ec2_elb_lb:
    name: "{{lb_name}}"
    state: present
    region: "{{region}}"
    security_group_ids: "{{web_sg.group_id}}"
    instance_ids:
      - "{{ web_server1.instances[0].id}}"
      - "{{ web_server2.instances[0].id}}"
    subnets:
      - "{{ lb1_subnet.subnet.id }}"
      - "{{ lb2_subnet.subnet.id }}" 
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
