---
- debug:
    var: vpc
- debug:
    var: igw
- debug:
    var: eip
- debug:
    var: ELB1_subnet
- debug:
    var: ELB2_subnet
- debug:
    var: application1_subnet
- debug:
    var: application2_subnet
- debug:
    var: database1_subnet
- debug:
    var: database2_subnet
- debug:
    var: public_routetable_ELB
- debug:
    var: private_routetable_app
- debug: 
    var: private_routetable_DB 


