---
- hosts: local
  vars_prompt:
    - name: "wb_sg_name"
      prompt: "Enter the name of the security group for web layer"
      private: no
    - name: "wb_sg_desc"
      prompt: "Enter the description of the security group for web layer"
      private: no
    - name: "wb_sg_rule_desc"
      prompt: "Enter the rule description "
      private: no
    - name: "app_sg_name"
      prompt: "Enter the name of the security group for application layer"
      private: no
    - name: "app_sg_desc"
      prompt: "Enter the description of the security group for application layer"
      private: no
    - name: "app_sg_rule_desc"
      prompt: "Enter the rule description "
      private: no
    - name: "app_protocol"
      prompt: "Enter the protocol for application layer "
      private: no
    - name: "app_port_no"
      prompt: "Enter the port number for application layer"
      private: no
    - name: "app_source_cidr"
      prompt: "Enter the source CIDR block for application layer"
      private: no
    - name: "db_sg_name"
      prompt: "Enter the name of the security group for database layer"
      private: no
    - name: "db_sg_desc"
      prompt: "Enter the description of the security group for database layer"
      private: no
    - name: "db_sg_rule_desc"
      prompt: "Enter the rule description for database layer "
      private: no
    - name: "db_protocol"
      prompt: "Enter the protocol for database layer "
      private: no
    - name: "db_port_no"
      prompt: "Enter the port number for database layer "
      private: no
    - name: "db_source_cidr"
      prompt: "Enter the source CIDR block for database layer "
      private: no

  tasks:
    - set_fact:
         wb_sg_name: "{{wb_sg_name}}"
         wb_sg_desc: "{{wb_sg_desc}}"
         wb_sg_rule_desc: "{{wb_sg_rule_desc}}"
         app_sg_name: "{{app_sg_name}}"
         app_sg_desc: "{{app_sg_desc}}"
         app_sg_rule_desc: "{{app_sg_rule_desc}}"
         app_protocol: "{{app_protocol}}"
         app_port_no: "{{app_port_no}}"
         app_source_cidr: "{{app_source_cidr}}"
         db_sg_name: "{{db_sg_name}}"
         db_sg_desc: "{{db_sg_desc}}"
         db_sg_rule_desc: "{{db_sg_rule_desc}}"
         db_protocol: "{{db_protocol}}"
         db_port_no: "{{db_port_no}}"
         db_source_cidr: "{{db_source_cidr}}"
         
  
  roles:
     - wb_security_group
     - app_security_group
     - db_security_group