---
- name: Creating VPC
  ec2_vpc_net:
          name: "{{vpc_name}}"
          region: "{{region}}"
          state: present
          cidr_block: "{{vpc_id}}"
          resource_tags: { "Environment":"{{tag_env}}" }
  register: vpc
 