---
- name: Creating web server 1
  ec2:
    region: "{{region}}"
    state: present
    keypair: "{{key_pair1}}"
    instance_tags: { "Name":"{{instance_name1}}" }
    image: ami-7c87d913
    instance_type: "{{ec2_type1}}"
    group: "{{sg1}}"
    vpc_subnet_id: "{{ web1_subnet.subnet.id }}"
    assign_public_ip: "{{public_ip1}}"
    wait: true
  register: web_server1

- name: Creating web server 2
  ec2:
    region: "{{region}}"
    state: present
    keypair: "{{key_pair1}}"
    instance_tags: { "Name":"{{instance_name2}}" }
    image: ami-7c87d913
    instance_type: "{{ec2_type2}}"
    group: "{{sg2}}"
    vpc_subnet_id: "{{ web2_subnet.subnet.id }}"
    assign_public_ip: "{{public_ip2}}"
    wait: true
  register: web_server2

- name: Creating application server 1
  ec2:
    region: "{{region}}"
    state: present
    keypair: "{{key_pair1}}"
    instance_tags: { "Name":"{{instance_name3}}" }
    image: ami-7c87d913
    instance_type: "{{ec2_type3}}"
    group: "{{sg3}}"
    vpc_subnet_id: "{{ application1_subnet.subnet.id }}"
    assign_public_ip: "{{public_ip3}}"
    wait: true
  register: app_server1

- name: Creating application server 2
  ec2:
    region: "{{region}}"
    state: present
    keypair: "{{key_pair1}}"
    instance_tags: { "Name":"{{instance_name4}}" }
    image: ami-7c87d913
    instance_type: "{{ec2_type4}}"
    group: "{{sg4}}"
    vpc_subnet_id: "{{ application2_subnet.subnet.id }}"
    assign_public_ip: "{{public_ip4}}"
    wait: true
  register: app_server2